### ISSUE TITLE
Enhance the tool to support automation test scripts

### ISSUE THREAD

**Issue by krishnam-pakalapati-git** [jqassistant-contrib/jqassistant-test-impact-analysis-plugin#2]
While the plugin right now is aimed to support unit tests level, the same idea if can be extended to support test automation scripts (API tests to start with), it would be more generic and advanced, so we want to generate something like - https://github.com/paul-hammant/maven-examples/blob/master/code-coverage-jacoco/src/integration-test/impact-map.txt

**Comment by StephanPirnbaum** [comment]
The plugin can be used to select only impacted integration test for the Maven Failsafe Plugin.
See: https://github.com/jqassistant-contrib/jqassistant-test-impact-analysis-plugin#integration-tests
